# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import property_service_pb2 as property__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in property_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PropertyServiceStub(object):
    """Define o serviço
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRecordByID = channel.unary_unary(
                '/PropertyService/GetRecordByID',
                request_serializer=property__service__pb2.RecordRequest.SerializeToString,
                response_deserializer=property__service__pb2.RecordResponse.FromString,
                _registered_method=True)
        self.CountRecords = channel.unary_unary(
                '/PropertyService/CountRecords',
                request_serializer=property__service__pb2.Empty.SerializeToString,
                response_deserializer=property__service__pb2.CountResponse.FromString,
                _registered_method=True)
        self.ExecuteXPath = channel.unary_unary(
                '/PropertyService/ExecuteXPath',
                request_serializer=property__service__pb2.QueryRequest.SerializeToString,
                response_deserializer=property__service__pb2.QueryResponse.FromString,
                _registered_method=True)


class PropertyServiceServicer(object):
    """Define o serviço
    """

    def GetRecordByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountRecords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteXPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PropertyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRecordByID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecordByID,
                    request_deserializer=property__service__pb2.RecordRequest.FromString,
                    response_serializer=property__service__pb2.RecordResponse.SerializeToString,
            ),
            'CountRecords': grpc.unary_unary_rpc_method_handler(
                    servicer.CountRecords,
                    request_deserializer=property__service__pb2.Empty.FromString,
                    response_serializer=property__service__pb2.CountResponse.SerializeToString,
            ),
            'ExecuteXPath': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteXPath,
                    request_deserializer=property__service__pb2.QueryRequest.FromString,
                    response_serializer=property__service__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PropertyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PropertyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PropertyService(object):
    """Define o serviço
    """

    @staticmethod
    def GetRecordByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PropertyService/GetRecordByID',
            property__service__pb2.RecordRequest.SerializeToString,
            property__service__pb2.RecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PropertyService/CountRecords',
            property__service__pb2.Empty.SerializeToString,
            property__service__pb2.CountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteXPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PropertyService/ExecuteXPath',
            property__service__pb2.QueryRequest.SerializeToString,
            property__service__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
